### PR TITLE
1407 bootstap list group test fix

### LINKED ISSUE #1407: Review all tests for the element and methods for that element in code and documentation: List group
In the context of #15 
Decomposition of #1336

Review all tests for the element and methods for that element in code and documentation.
Element name: List group

1. Check if the given element has all methods in the documentation described - add missing methods (not ALL possible methods but methods that make sense for given element - i.e. applicable for it)
2. Add missing methods into documentation
3. Check if all methods covered with tests
4. Add missing tests to get all element methods covered

### PR DESCRIPTION
**Pull request by NataliaTikhomirova**
#1407

### CODE REVIEW

File: jdi-light-bootstrap-tests/src/test/java/io/github/epam/bootstrap/tests/composite/section/listGroup/DisabledItemsTests.java [hunk 1]
```diff
@@ -59,10 +60,15 @@ public void listGroupTextTests(int num, String text) {
     }
 
     @Test(dataProvider = "listData")
-    public void listGroupClassesIsValidationTests(int num, String text) {
-        listGroupDisabledItems.listGroup.get(num).is()
+    public void listGroupClassesTextValidationTests(int num, String text) {
+        Assert.assertEquals(listGroupDisabledItems.listGroup.get(num).getText(), text);
```
Comment (splekhanov) [inline jdi-light-bootstrap-tests/src/test/java/io/github/epam/bootstrap/tests/composite/section/listGroup/DisabledItemsTests.java]: Lets use JDI asserts in tests for bootstrap instead of bare testNG's:
listGroupDisabledItems.listGroup.get(num).is().text(text);
